In [1]:
import matplotlib.pyplot as plt
import numpy as np
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score

In [1]:
import matplotlib.pyplot as plt
import numpy as np
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score

#formula Y = X1 + 2*X2 + 0.5*X3 + noise (we want ridge and lasso to remove this noise)
X = [[1,2,4, 1000],[2,4,6, 45321],[4,3,3,45112],[4,6,1,1478],[5,7,4,1256],[1,9,100,1256], [3,5,56,12], [5,3,4,1236], [7,0,6,1258]]
Y = [[7],[14],[12.5],[14.5],[21],[73], [41], [21], [10]]

regr = linear_model.LinearRegression()

# Train the model using the training sets
regr.fit(X, Y)



LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [5]:
# Make predictions using the testing set
X_test = [[1,4,5,458],[20,3,5,4523],[40,6,3,1258],[30,0,2,12479],[16,0,70,12369],[60,1,5,1478]]
Y_pred = regr.predict(X_test)

'''
highly accurate 

array([[11.95217108],
       [32.2749752 ],
       [60.07906029],
       [36.80870469],
       [56.70557135],
       [75.25404103]])
       
'''
print(Y_pred)
print('Coefficients: \n', regr.coef_)

[[11.79948112]
 [32.60358121]
 [60.87795429]
 [37.41430889]
 [57.07322125]
 [76.52191928]]
Coefficients: 
 [[1.19088340e+00 1.84874021e+00 5.34293898e-01 6.40974698e-06]]


In [12]:
from sklearn.linear_model import Ridge

rmodel = Ridge(alpha=1)
rmodel.fit(X,Y)
r_Y_pred = rmodel.predict(X_test)
print(r_Y_pred)
print(rmodel.coef_)

[[12.00388727]
 [31.58620627]
 [58.35665872]
 [35.88193505]
 [56.51398631]
 [72.95158157]]
[[1.12401668e+00 1.79120218e+00 5.34834563e-01 4.23230952e-06]]


In [14]:
from sklearn.linear_model import Lasso

lmodel = Lasso(alpha=0.1)
lmodel.fit(X,Y)
l_Y_pred = lmodel.predict(X_test)
print(l_Y_pred)
print(lmodel.coef_)

[11.96032301 31.82932822 59.00838406 36.21482168 56.56152257 73.7951205 ]
[1.14041188e+00 1.81811488e+00 5.34014548e-01 4.74647809e-06]
